MyList = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(MyList[0])
print(MyList[2])
print(MyList[5])
print(MyList[:2])
print(MyList[5:])
print(MyList[2:5])
print(MyList[-1])
print(MyList[-4])
print(MyList[-1:])
print(MyList[:-4])
print(MyList[-4:-1])